### ISSUE TITLE
电池支持最大多长时间？ ---续航与win10下没有什么差别，个人感觉MAC下续航还有增加。

### ISSUE THREAD

**Issue by hawkinchina** [whtiehack/XiaoMi-Air#10]
电池支持最大多长时间？ ---续航与win10下没有什么差别，个人感觉MAC下续航还有增加。

可以把亮度调节到只有一格的情况下， 最长时间？？

我13.3 指纹版 10.13.4  
处理器名称：	Intel Core i5
  处理器速度：	1.80 GHz

**Comment by hawkinchina** [comment]
充满电，可以使用4个小时，最长时间， 测试多次。。。

**Comment by whtiehack** [comment]
4小时不错了吧。你在win10底下多长时间？

**Comment by hawkinchina** [comment]
@whtiehack 我的本子，买回来，就删除了win10，安装了macos， 但是官方宣称win10，7，8，个小时把。。
下面是小米的官方信息：
电池电源
40瓦时(Typ) / 39瓦时(Min) 轻薄电池，两串两并 4cell 锂离子聚合物电芯，最高 578Wh/L 能量密度电池
支持 1C 快充，30分钟充电50%，USB-C电源适配端口
在线视频播放 8小时，本地视频播放 7.5小时，网页浏览 7.5小时

**Comment by whtiehack** [comment]
官方说的应该是达不到的吧。你可以查查别人和你同一型号的本win10能用多长时间。

**Comment by hawkinchina** [comment]
你用的电脑，可以多长时间？？

**Comment by whtiehack** [comment]
看电影  4 5个小时这样子吧。
