### ISSUE TITLE
为啥我不能调节亮度

### ISSUE THREAD

**Issue by xiangsanliu** [whtiehack/XiaoMi-Air#11]
偏好设置里找不到亮度条

**Comment by whtiehack** [comment]
https://github.com/whtiehack/XiaoMi-Air#%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98

**Comment by xiangsanliu** [comment]
感谢，但是我连那个亮度条都没有。
最后换了 https://github.com/sakoula/XiaoMi-Air-6200U 这个项目的efi成功了。

**Comment by whtiehack** [comment]
@xiangsanliu  感谢分享，我看了一下。 这个项目有一个 `SSDT-CKEY.aml Native brightness hotkey support`.

另外请问一下你安装OS X是哪个版本？ 有什么其它问题吗？

**Comment by xiangsanliu** [comment]
嗯嗯。
我现在用的是mojave14.4，刚刚更新的，目前没发现什么问题。（@sakoula 的项目的clover从14.3更新到14.4会失败，我更新到最新的Clover后才可以更新。）

**Comment by xiangsanliu** [comment]
发现问题了，电池始终显示0%，这个电池配置是在哪个文件呀

**Comment by whtiehack** [comment]
13.x 电源是原生支持了。。不知道14.4怎么就不支持了。

**Comment by xiangsanliu** [comment]
emmm...我再想想办法，不行就只能退回13.x了😅

**Comment by whtiehack** [comment]
oc版的最新efi 可以用那键盘控制声音和亮度了
