### ISSUE TITLE
找到新EFI

### ISSUE THREAD

**Issue by ferristale** [whtiehack/XiaoMi-Air#14]
可以参考[这位老兄](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen#what-is-working)的repo，更新也很勤

目前除了wifi，其他硬件功能完好

但是系统安装的话不太建议大家使用他里面的方法，除非你在安装阶段就可以联网

可以用黑果小兵的安装包，替换EFI就行了

**Comment by ohhhr** [comment]
你合盖再打开后usb还可以用吗？

**Comment by whtiehack** [comment]
os x 10.13.5   i5-6200u 这个仓库的EFI,稳定至今
