### ISSUE TITLE
可以将蓝牙开启么？

### ISSUE THREAD

**Issue by ggggiaqgyd** [whtiehack/XiaoMi-Air#15]
用了efi之后，无法找到蓝牙的图标。之前用其它efi是可以使用虚拟机开启蓝牙。

**Comment by whtiehack** [comment]
蓝牙被屏蔽了



https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/%E8%93%9D%E7%89%99%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88

**Comment by whtiehack** [comment]
新的oc版efi 支持wifi和 蓝牙了.
