### ISSUE TITLE
外接显示器

### ISSUE THREAD

**Issue by keshawnhsieh** [whtiehack/XiaoMi-Air#21]
看 [sakoula/XiaoMi-Air-6200U](https://github.com/sakoula/XiaoMi-Air-6200U)的说明中No audio output from HDMI port。
您的这个版本是否也无法输出外接HDMI显示器

**Comment by whtiehack** [comment]
没试过声音输出 只试过视频输出 只能输出2k的

**Comment by keshawnhsieh** [comment]
> 没试过声音输出 只试过视频输出 只能输出2k的

感谢。视频输出已经可以满足我的需求。
