### ISSUE TITLE
睡眠后usb失效

### ISSUE THREAD

**Issue by qq923500488** [whtiehack/XiaoMi-Air#4]
楼主幸会，感谢您的辛勤努力为AIR用户带来了福音。我按照您说的将  如果可能，使硬盘进入休眠  关闭了，但是失眠之后依然无法唤醒usb设备，而且在充电睡眠时经常睡死。本人小白，如有操作错误还望楼主给与指点，谢谢

**Comment by whtiehack** [comment]
电源管理还有问题。 不插电一般没问题。 插电就会有问题，要改ACPI，暂时还没研究透呢。

**Comment by qq923500488** [comment]
谢谢楼主解答，辛苦了

**Comment by xiaoyu233** [comment]
首先感谢分享，我的小米13.3，同样会睡眠后usb失效，还有开机触摸板双指右键不能用，非要进设置重新选双指右键才生效。其他基本没啥问题

**Comment by whtiehack** [comment]
@xiaoyu233 换用这里的 触摸板驱动试试。

**Comment by xiaoyu233** [comment]
@whtiehack 好的，先试试
