### ISSUE TITLE
如何设置快捷键调节亮度啊？

### ISSUE THREAD

**Issue by aaron2wh** [whtiehack/XiaoMi-Air#5]
我在系统设置里面没有看见这个条目啊？愿闻其详！
![2018-09-14 5 16 13](https://user-images.githubusercontent.com/43267693/45543444-0de37780-b847-11e8-912b-58107b40657a.png)

**Comment by ruter** [comment]
> 我在系统设置里面没有看见这个条目啊？愿闻其详！
> ![2018-09-14 5 16 13](https://user-images.githubusercontent.com/43267693/45543444-0de37780-b847-11e8-912b-58107b40657a.png)

![image](https://user-images.githubusercontent.com/8568876/45810394-24814700-bcfd-11e8-9fea-932a73f72337.png)

显示器这个，开启 HiDPI 后

@aaron2wh

**Comment by aaron2wh** [comment]
> > 我在系统设置里面没有看见这个条目啊？愿闻其详！
> > ![2018-09-14 5 16 13](https://user-images.githubusercontent.com/43267693/45543444-0de37780-b847-11e8-912b-58107b40657a.png)
> 
> ![image](https://user-images.githubusercontent.com/8568876/45810394-24814700-bcfd-11e8-9fea-932a73f72337.png)
> 
> 显示器这个，开启 HiDPI 后
> 
> @aaron2wh

请问安装HiDPI的时候，终端以下选择，应该选择哪一个啊？
(1) OPEN HIDPI
(2) OPEN HIDPI (Inject EDID)
(3) CLOSE HIDPI

Enter your choice[1~3]:

**Comment by ruter** [comment]
> > > 我在系统设置里面没有看见这个条目啊？愿闻其详！
> > > ![2018-09-14 5 16 13](https://user-images.githubusercontent.com/43267693/45543444-0de37780-b847-11e8-912b-58107b40657a.png)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/8568876/45810394-24814700-bcfd-11e8-9fea-932a73f72337.png)
> > 显示器这个，开启 HiDPI 后
> > @aaron2wh
> 
> 请问安装HiDPI的时候，终端以下选择，应该选择哪一个啊？
> (1) OPEN HIDPI
> (2) OPEN HIDPI (Inject EDID)
> (3) CLOSE HIDPI
> 
> Enter your choice[1~3]:

好像是1，当时装好之后打开是没有亮度调节的快捷键设置的，好像用HDMI外接之后就出现了，具体原因不明，你可以测试一下

**Comment by whtiehack** [comment]
新的OC版可以直接用键盘控制了.
