### ISSUE TITLE
更新EFI

### ISSUE THREAD

**Issue by fgksgf** [whtiehack/XiaoMi-Air#7]
你好，我按照你的方法成功安装了黑苹果（相同机型），但是耳机没声音，有时睡眠唤醒后usb全都失效。

想请问下你现在用的还是这个仓库的efi文件吗，有没有使用最新的小米pro的efi呢？

**Comment by whtiehack** [comment]
我一直在用这个EFI， 耳机要调声道，看readme.  

睡眠唤醒USB失效是插上电源的原因，不插电源应该是没有这个问题。

所以我现在都取消睡眠的，把 “使用电源时阻止睡眠勾上”。



现在的EFI能用，相对来说也比较完美了，不太想折腾了，所以没有研究别的EFI了。

**Comment by fgksgf** [comment]
好的，感谢你的回复
