### ISSUE TITLE
关机后，电脑还是亮着，没有正常关机

### ISSUE THREAD

**Issue by asushugo** [whtiehack/XiaoMi-Air#8]
关机后，电脑的LED还是亮着，没有正常关机，需长按关机，请大佬帮忙解决

**Comment by whtiehack** [comment]
你什么版本的本子？装的什么版本的系统？

**Comment by whtiehack** [comment]
把 RT2870USBWirelessDriver.kext 删掉试试 。  这个是我后加进去的 usb wifi驱动。

**Comment by asushugo** [comment]
小米笔记本Air 13.3 i5-6200U
系统版本是10.13.6
我试试

**Comment by whtiehack** [comment]
你也可以试一下10.13.5  我用的是10.13.5。  我的和你的一样 13.3  i5-6200u

**Comment by asushugo** [comment]
release里面有untagged标记的我是可以正常启动黑苹果的，但是master的不行，启动到一半就会重启
不知道为什么

**Comment by calors** [comment]
> release里面有untagged标记的我是可以正常启动黑苹果的，但是master的不行，启动到一半就会重启
> 不知道为什么

10.13.6开始有问题，10.14也一样。 建议可以保持在10.13.5

**Comment by Gav1nMa** [comment]
小米笔记本Air 13.3 i5-6200U
系统版本是10.13.6
同样遇到这个问题，目前的手动解决办法是关机后，再次长按电源键，直至电源银LED灯熄灭，至此，已完全关机。
